### ISSUE TITLE
Link error with Xcode 9, macOS 10.13

### ISSUE THREAD

**Issue by Uncommon** [libgit2/objective-git#638]
I get this linker error when I try to build:

```
Undefined symbols for architecture x86_64:
  "_http_errno_description", referenced from:
      _http_stream_read in libgit2.a(http.c.o)
  "_http_parser_execute", referenced from:
      _http_stream_read in libgit2.a(http.c.o)
  "_http_parser_init", referenced from:
      _clear_parser_state in libgit2.a(http.c.o)
  "_http_parser_parse_url", referenced from:
      _gitno_extract_url_parts in libgit2.a(netops.c.o)
  "_http_should_keep_alive", referenced from:
      _http_connect in libgit2.a(http.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The error seemed to start when I upgraded to 10.13, where I was running Xcode 9 on 10.12.

Any ideas?

**Comment by Uncommon** [comment]
I've confirmed that this will be fixed by libgit2/libgit2#4339. Thanks to @carlosmn for pointing me that way.
