### PR TITLE
Add matrix build for iOS and Mac

### PR DESCRIPTION
**Pull request by pietbrauer**
If this works then the time builds will take is only half as we split the build for Mac and iOS to separate machines.

### CODE REVIEW

**Comment by phatblat** [comment]
```
../SwiftSpec.swift:11:8: error: module file's minimum deployment target is ios9.2 v9.2: /Users/travis/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-dggdbcqvjtimfddtjpjrzodjcbls/Build/Products/Debug-iphonesimulator/Quick.framework/Modules/Quick.swiftmodule/x86_64.swiftmodule
import Quick
```

This is an odd error because there are no targets that I can find that have a deployment target of iOS 9.2. Based on the SO post below, I suspect this is might be related to the iOS Tests target being raised to `9.0`.

http://stackoverflow.com/questions/31461012/can-no-longer-import-app-module-into-unit-tests-after-changing-deployment-target

I can't reproduce this locally so can't tell if this would resolve the issue. Why was the Test deployment target raised?

**Comment by pietbrauer** [comment]
I think I did that to fix other errors regarding the Quick update which now only works with iOS 9.0? Will try to dig into it today.

**Comment by pietbrauer** [comment]
@phatblat Green now, seems to be related to Xcode 7.2

**Comment by phatblat** [comment]
Works for me
